Downloads/demo-fcafe-demo-v2/config/routes.rb
Rails.application.routes.draw do
  root "staticpages#index"
  devise_for :users

  resources :suggestions, except: [:update, :show, :edit]
  resources :shops
  resources :rates

  namespace :admin do
    get "/" => "staticpages#index"
    resources :requests
    resources :shop_types
    resources :categories
    resources :users, except: [:new, :create, :edit]
  end

  namespace :shop_owner do
  	resources :suggestions, only: [:index, :update, :destroy]
    resources :shops
    resources :albums
    resources :categories, except: :show
  end
end

Downloads/demo-fcafe-demo-v2/app/views/admin/layouts/_header.html.erb
<div id="main-container">
  <div id="page-content">
    <div class="content-header">
      <ul class="nav-horizontal text-center">
        <li class="active">
          <%= link_to admin_shop_types_path do %>
            <i class="fa fa-bar-chart"></i><%= t ".shop_types" %>
          <% end %>
        </li>
        <li>
          <%= link_to admin_requests_path do %>
            <i class="fa fa-ambulance"></i><%= t "requests" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="gi gi-shopping_cart"></i>
            <%= t "shop" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="gi gi-shopping_bag"></i>
            <%= t "product" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

Downloads/demo-fcafe-demo-v2/app/views/admin/layouts/_left_bar.html.erb
<div id="sidebar">
  <div id="sidebar-scroll">
    <div class="sidebar-content">
      <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
        <div class="sidebar-user-avatar">
          <a href="page_ready_user_profile.html">
            <img src="" alt="avatar">
          </a>
        </div>
        <div class="sidebar-user-name"><%= t ".username" %></div>
        <div class="sidebar-user-links">
          <a href="page_ready_user_profile.html" data-toggle="tooltip"
            data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
          <a href="#modal-user-settings" data-toggle="modal" class="enable-toolti"
            data-placement="bottom" title="Settings"><i class="gi gi-cogwheel"></i></a>
          <a href="login.html" data-toggle="tooltip" data-placement="bottom"
            title="Logout"><i class="gi gi-exit"></i></a>
        </div>
      </div>
      <ul class="sidebar-nav">
        <li>
          <a href="index.html"><i class="gi gi-stopwatch sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide"><%= t ".dashboard" %></span>
          </a>
        </li>
        <li class="active">
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left
            sidebar-nav-indicator sidebar-nav-mini-hide"></i>
            <i class="gi gi-shopping_cart sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide"><%= t ".dropdown" %></span>
          </a>
          <ul>
            <li>
              <%= link_to t(".shop_types"), admin_shop_types_path %>
            </li>
            <li>
              <%= link_to t(".categories"), admin_categories_path %>
            </li>
            <li>
              <%= link_to t(".requests"), admin_requests_path %>
            </li>
            <li>
              <a href=""><%= t ".shop" %></a>
            </li>
            <li>
              <%= link_to t(".users"), admin_users_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>