Downloads/demo-fcafe-demo-v2/config/routes.rb
Rails.application.routes.draw do
  root "staticpages#index"
  devise_for :users

  resources :suggestions, except: [:update, :show, :edit]
  resources :shops
  resources :rates

  namespace :admin do
    get "/" => "staticpages#index"
    resources :requests
    resources :shop_types
    resources :categories
    resources :users, except: [:new, :create, :edit]
  end

  namespace :shop_owner do
  	resources :suggestions, only: [:index, :update, :destroy]
    resources :shops
    resources :albums
    resources :categories, except: :show
  end
end

Downloads/demo-fcafe-demo-v2/app/models/album.rb
class Album < ApplicationRecord
  has_many :images, dependent: :destroy

  has_one :shop

  validates_uniqueness_of :name, scope: :shop_id

  scope :order_date_desc, -> {order created_at: :desc}
  scope :album_by_shop, -> shop_id do
    where shop_id: shop_id
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/albums_controller.rb
class ShopOwner::AlbumsController < ApplicationController
  layout "shop_owner_layout"
  before_action :load_album, only: [:edit, :update, :destroy]

  def index
    @album = Album.new
    @albums = Album.order_date_desc.album_by_shop(params[:id])
      .paginate page: params[:page], per_page: Settings.per_page
    @shop_id = params[:id]
  end

  def create
    @album = Album.new album_params
    if @album.save
      flash[:success] = t "create_complete"
    else
      flash[:danger] = t "not_create"
    end
    redirect_to :back
  end

  def edit
    @edit_page = params[:action]
  end

  def update
    if @album.update_attributes album_params
      flash[:success] = t "album_updated"
    else
      flash[:danger] = t "album_not_update"
    end
    redirect_to shop_owner_albums_path(id: @album.shop_id)
  end

  def destroy
    if @album.destroy
      flash[:success] = t "del_complete"
    else
      flash[:danger] = t "not_delete"
    end
    redirect_to :back
  end

  private
  def album_params
    params.require(:album).permit :name, :shop_id
  end

  def load_album
    @album = Album.find_by id: params[:id]
    unless @album
      flash[:danger] = t "album_not_found"
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/categories_controller.rb
class ShopOwner::CategoriesController < ApplicationController
  layout "shop_owner_layout"
  
  load_and_authorize_resource

  before_action :load_list_category, only: [:new, :edit]
  
  def index
    params[:shop_id] ||= current_user.shops.first.id
    @categories = Category.by_shop(params[:shop_id]).newest
      .paginate page: params[:page], per_page: Settings.categories.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @parent_category = Category.find_by id: category_params[:parent_id]
    if @parent_category && @parent_category.products.any?
      flash[:danger] = t(".relationship_error", name: @parent_category.name,
        num_product: @parent_category.products.size)
    else 
      @category = Category.find_or_create_by category_params 
      if @category.save
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".category_existed"
      end
    end
    redirect_to shop_owner_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to shop_owner_categories_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.leaf? 
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_error"
      end
    else 
      flash[:danger] = t ".relationship_error"
    end
    redirect_to shop_owner_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id, :shop_id
  end

  def load_list_category
    @categories = Category.all
    unless @categories
      flash[:danger] = t ".not_found"
      redirect_to shop_owner_categories_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/shops_controller.rb
class ShopOwner::ShopsController < ApplicationController
  layout "shop_owner_layout"

  load_and_authorize_resource

  def index
    @shops = Shop.order_date_desc.shop_by_user(current_user.id).approved
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def edit
    @shop_types = ShopType.all
  end

  def update
    if @shop.update_attributes shop_params
      flash[:success] = t "shop_updated"
      redirect_to shop_owner_shops_path
    else
      render :edit
    end
  end

  def destroy
    if @shop.destroy
      flash[:success] = t "del_complete"
    else
      flash[:danger] = t "not_delete"
    end
    redirect_to shop_owner_shops_path
  end

  private
  def shop_params
    params.require(:shop).permit :name, :description, :address, :user_id,
      :avatar, :shop_type_id
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/suggestions_controller.rb
class ShopOwner::SuggestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_suggestion, only: [:update, :destroy]

  layout "shop_owner_layout"
  
  def index
    @supports = Supports::SuggestionSupport.new params[:page]
  end

  def update
    @suggestion.update_attributes status: params[:value]
    if @suggestion.save
      flash[:success] = t(".update_success", product: @suggestion.name, 
        status: @suggestion.status)
    else
      flash[:danger] = t(".update_error", product: @suggestion.name, 
        status: @suggestion.status)
    end
    redirect_to shop_owner_suggestions_path
  end

  def destroy
    if @suggestion.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to shop_owner_suggestions_path
  end

  private
  def load_suggestion
    @suggestion = Suggestion.find_by id: params[:id]
    unless @suggestion
      flash[:danger] = t ".not_found"
      redirect_to shop_owner_suggestions_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/albums/_form_album.html.erb
<section class="site-content site-section">
  <% if @edit_page == Settings.action_edit %>
    <h3 class="col-md-6 col-md-offset-3"><%= t "edit_album" %></h3>
  <% else %>
    <h3 class="center"><%= t "add_album" %></h3>
  <% end %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for [:shop_owner, @album] do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, required: true %>

        <% unless @edit_page == Settings.action_edit %>
          <%= f.hidden_field :shop_id, value: @shop_id %>
        <% end %>

        <%= f.submit (t "add"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</section>

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/albums/edit.html.erb
<%= render partial: "form_album", locals: {shop_id: @shop_id} %>

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/albums/index.html.erb
<button type = "button" class = "btn btn-info" data-toggle = "modal"
  data-target = "#ModalAlbum"><%= t "new_album" %></button>
<table class="table table-vcenter table-striped">
  <tr>
    <th><%= t "name" %></th>
    <th colspan="2"><%= t "action" %></th>
  </tr>
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.name %></td>
      <td>
        <div class="btn-group btn-group-xs">
          <%= link_to edit_shop_owner_album_path(album),
            class: "btn btn-default" do %>
            <i class="fa fa-pencil"><%= t "edit" %></i>
          <% end %>
        </div>
      </td>
      <td>
        <%= link_to shop_owner_album_path(album), method: :delete,
          data: {confirm: t("sure")}, class: "btn btn-danger" do %>
          <i class="fa fa-times"><%= t "delete" %></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<div id = "ModalAlbum" class = "modal fade" role = "dialog">
  <div class = "modal-dialog modal-lg">
    <div class = "modal-content">
      <%= render "form_album" %>
      <div class = "modal-footer">
        <button type = button" class = "btn btn-default"
          data-dismiss = "modal"><%= t "close" %></button>
      </div>
    </div>
  </div>
</div>