Downloads/demo-fcafe-demo-v2/config/routes.rb
Rails.application.routes.draw do
  root "staticpages#index"
  devise_for :users

  resources :suggestions, except: [:update, :show, :edit]
  resources :shops
  resources :rates

  namespace :admin do
    get "/" => "staticpages#index"
    resources :requests
    resources :shop_types
    resources :categories
    resources :users, except: [:new, :create, :edit]
  end

  namespace :shop_owner do
  	resources :suggestions, only: [:index, :update, :destroy]
    resources :shops
    resources :albums
    resources :categories, except: :show
  end
end

Downloads/demo-fcafe-demo-v2/app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  belongs_to :shop

  has_many :products, dependent: :destroy

  validates :name, presence: true, 
    length: {maximum: Settings.categories.name_max_length}, 
    uniqueness: true

  scope :newest, ->{order created_at: :desc}
  scope :by_shop, ->shop_id do
    where("shop_id = ? or shop_id is null", shop_id)
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin_layout"
  
  before_action :load_category, only: [:edit, :update, :destroy]
  before_action :load_list_category, only: [:new, :edit]
  
  def index
    @categories = Category.newest.paginate page: params[:page],
      per_page: Settings.categories.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @parent_category = Category.find_by id: category_params[:parent_id]
    if @parent_category && @parent_category.products.any?
      flash[:danger] = t(".relationship_error", name: @parent_category.name,
        num_product: @parent_category.products.size)
    else 
      @category = Category.find_or_create_by category_params 
      if @category.save
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".category_existed"
      end
    end
    redirect_to admin_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.leaf? 
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_error"
      end
    else 
      flash[:danger] = t ".relationship_error"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id
  end

  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t ".not_found"
      redirect_to admin_categories_path
    end
  end

  def load_list_category
    @categories = Category.all
    unless @categories
      flash[:danger] = t ".not_found"
      redirect_to admin_categories_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/categories_controller.rb
class ShopOwner::CategoriesController < ApplicationController
  layout "shop_owner_layout"
  
  load_and_authorize_resource

  before_action :load_list_category, only: [:new, :edit]
  
  def index
    params[:shop_id] ||= current_user.shops.first.id
    @categories = Category.by_shop(params[:shop_id]).newest
      .paginate page: params[:page], per_page: Settings.categories.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @parent_category = Category.find_by id: category_params[:parent_id]
    if @parent_category && @parent_category.products.any?
      flash[:danger] = t(".relationship_error", name: @parent_category.name,
        num_product: @parent_category.products.size)
    else 
      @category = Category.find_or_create_by category_params 
      if @category.save
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".category_existed"
      end
    end
    redirect_to shop_owner_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to shop_owner_categories_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.leaf? 
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_error"
      end
    else 
      flash[:danger] = t ".relationship_error"
    end
    redirect_to shop_owner_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id, :shop_id
  end

  def load_list_category
    @categories = Category.all
    unless @categories
      flash[:danger] = t ".not_found"
      redirect_to shop_owner_categories_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], html: {multipart: true,
  class: "form-horizontal category-form", id: "category_form"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="control-group">
    <%= f.label :parent_name %>
    <%= f.select :parent_id, @categories.collect{|ctgr| [ctgr.name, ctgr.id]},
      {include_blank: t(".none")}, {class: "form-control"} %>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :name, t(".category_name") %>
    <div class="controls">
      <%= f.text_field :name, class: "form-control", id: "name",
        placeholder: t(".category_name") %>
    </div>
  </div>
  <br>
  <div class="form-actions add-category">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <%= link_to t(".cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

Downloads/demo-fcafe-demo-v2/app/views/admin/categories/edit.html.erb
<% provide :button_text, t(".edit_category") %>
<div id="main-container">
  <div id="page-content">
    <div class="block full">
      <div class="block-title">
        <h2><strong><%= t ".edit_category" %> </strong></h2>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

Downloads/demo-fcafe-demo-v2/app/views/admin/categories/index.html.erb
<div id="main-container">
  <div id="page-content">
    <div class="block full">
      <div class="block-title">
        <h2><strong><%= t ".categories" %> </strong><%= t ".overview" %></h2>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= link_to t(".new_category"), new_admin_category_path,
            class: "btn btn-info" %>
          <hr>
          <div class="table-responsive">
            <table class="table table-vcenter table-striped">
              <tr class="display-categories">
                <th class="index text-center"><%= t".id" %></th>
                <th class="text-center"><%= t ".name" %></th>
                <th class="text-center"><%= t ".parent_id" %></th>
                <th class="text-center"><%= t ".action" %></th>
              </tr>
              <% @categories.each do |category| %>
                <tr class="display-categories">
                  <td class="index text-center"><%= category.id %></td>
                  <td class="text-center"><%= category.name %></td>
                  <td class="text-center">
                    <% if category.parent_id.blank? %>
                      <%= t ".root" %>
                    <% else %>
                      <%= category.parent_id %>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <%= link_to edit_admin_category_path(category),
                      class: "btn btn-default" do %>
                      <i class="fa fa-pencil-square-o"><%= t ".edit" %></i>
                    <% end %>
                    <%= link_to admin_category_path(category), method: :delete,
                      data: {confirm: t("sure")}, class: "btn btn-danger" do %>
                      <i class="fa fa-trash"><%= t ".delete" %></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>  
</section>

Downloads/demo-fcafe-demo-v2/app/views/admin/categories/new.html.erb
<% provide :button_text, t(".new_category") %>
<div id="main-container">
  <div id="page-content">
    <div class="block full">
      <div class="block-title">
        <h2><strong><%= t ".new_category" %> </strong></h2>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>