Downloads/demo-fcafe-demo-v2/config/routes.rb
Rails.application.routes.draw do
  root "staticpages#index"
  devise_for :users

  resources :suggestions, except: [:update, :show, :edit]
  resources :shops
  resources :rates

  namespace :admin do
    get "/" => "staticpages#index"
    resources :requests
    resources :shop_types
    resources :categories
    resources :users, except: [:new, :create, :edit]
  end

  namespace :shop_owner do
  	resources :suggestions, only: [:index, :update, :destroy]
    resources :shops
    resources :albums
    resources :categories, except: :show
  end
end

Downloads/demo-fcafe-demo-v2/app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  belongs_to :shop

  has_many :products, dependent: :destroy

  validates :name, presence: true, 
    length: {maximum: Settings.categories.name_max_length}, 
    uniqueness: true

  scope :newest, ->{order created_at: :desc}
  scope :by_shop, ->shop_id do
    where("shop_id = ? or shop_id is null", shop_id)
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin_layout"
  
  before_action :load_category, only: [:edit, :update, :destroy]
  before_action :load_list_category, only: [:new, :edit]
  
  def index
    @categories = Category.newest.paginate page: params[:page],
      per_page: Settings.categories.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @parent_category = Category.find_by id: category_params[:parent_id]
    if @parent_category && @parent_category.products.any?
      flash[:danger] = t(".relationship_error", name: @parent_category.name,
        num_product: @parent_category.products.size)
    else 
      @category = Category.find_or_create_by category_params 
      if @category.save
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".category_existed"
      end
    end
    redirect_to admin_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.leaf? 
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_error"
      end
    else 
      flash[:danger] = t ".relationship_error"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id
  end

  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t ".not_found"
      redirect_to admin_categories_path
    end
  end

  def load_list_category
    @categories = Category.all
    unless @categories
      flash[:danger] = t ".not_found"
      redirect_to admin_categories_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/albums_controller.rb
class ShopOwner::AlbumsController < ApplicationController
  layout "shop_owner_layout"
  before_action :load_album, only: [:edit, :update, :destroy]

  def index
    @album = Album.new
    @albums = Album.order_date_desc.album_by_shop(params[:id])
      .paginate page: params[:page], per_page: Settings.per_page
    @shop_id = params[:id]
  end

  def create
    @album = Album.new album_params
    if @album.save
      flash[:success] = t "create_complete"
    else
      flash[:danger] = t "not_create"
    end
    redirect_to :back
  end

  def edit
    @edit_page = params[:action]
  end

  def update
    if @album.update_attributes album_params
      flash[:success] = t "album_updated"
    else
      flash[:danger] = t "album_not_update"
    end
    redirect_to shop_owner_albums_path(id: @album.shop_id)
  end

  def destroy
    if @album.destroy
      flash[:success] = t "del_complete"
    else
      flash[:danger] = t "not_delete"
    end
    redirect_to :back
  end

  private
  def album_params
    params.require(:album).permit :name, :shop_id
  end

  def load_album
    @album = Album.find_by id: params[:id]
    unless @album
      flash[:danger] = t "album_not_found"
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/categories_controller.rb
class ShopOwner::CategoriesController < ApplicationController
  layout "shop_owner_layout"
  
  load_and_authorize_resource

  before_action :load_list_category, only: [:new, :edit]
  
  def index
    params[:shop_id] ||= current_user.shops.first.id
    @categories = Category.by_shop(params[:shop_id]).newest
      .paginate page: params[:page], per_page: Settings.categories.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @parent_category = Category.find_by id: category_params[:parent_id]
    if @parent_category && @parent_category.products.any?
      flash[:danger] = t(".relationship_error", name: @parent_category.name,
        num_product: @parent_category.products.size)
    else 
      @category = Category.find_or_create_by category_params 
      if @category.save
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".category_existed"
      end
    end
    redirect_to shop_owner_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to shop_owner_categories_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.leaf? 
      if @category.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_error"
      end
    else 
      flash[:danger] = t ".relationship_error"
    end
    redirect_to shop_owner_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :parent_id, :shop_id
  end

  def load_list_category
    @categories = Category.all
    unless @categories
      flash[:danger] = t ".not_found"
      redirect_to shop_owner_categories_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/shops_controller.rb
class ShopOwner::ShopsController < ApplicationController
  layout "shop_owner_layout"

  load_and_authorize_resource

  def index
    @shops = Shop.order_date_desc.shop_by_user(current_user.id).approved
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def edit
    @shop_types = ShopType.all
  end

  def update
    if @shop.update_attributes shop_params
      flash[:success] = t "shop_updated"
      redirect_to shop_owner_shops_path
    else
      render :edit
    end
  end

  def destroy
    if @shop.destroy
      flash[:success] = t "del_complete"
    else
      flash[:danger] = t "not_delete"
    end
    redirect_to shop_owner_shops_path
  end

  private
  def shop_params
    params.require(:shop).permit :name, :description, :address, :user_id,
      :avatar, :shop_type_id
  end
end

Downloads/demo-fcafe-demo-v2/app/controllers/shop_owner/suggestions_controller.rb
class ShopOwner::SuggestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_suggestion, only: [:update, :destroy]

  layout "shop_owner_layout"
  
  def index
    @supports = Supports::SuggestionSupport.new params[:page]
  end

  def update
    @suggestion.update_attributes status: params[:value]
    if @suggestion.save
      flash[:success] = t(".update_success", product: @suggestion.name, 
        status: @suggestion.status)
    else
      flash[:danger] = t(".update_error", product: @suggestion.name, 
        status: @suggestion.status)
    end
    redirect_to shop_owner_suggestions_path
  end

  def destroy
    if @suggestion.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to shop_owner_suggestions_path
  end

  private
  def load_suggestion
    @suggestion = Suggestion.find_by id: params[:id]
    unless @suggestion
      flash[:danger] = t ".not_found"
      redirect_to shop_owner_suggestions_path
    end
  end
end

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/categories/_form.html.erb
<%= form_for [:shop_owner, @category], html: {multipart: true,
  class: "form-horizontal category-form", id: "category_form"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="control-group">
    <%= f.label :shop_name %>
    <%= f.select :shop_id, current_user.shops.collect{|ctgr| [ctgr.name, ctgr.id]},
      {}, {class: "form-control"} %>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :parent_name %>
    <%= f.select :parent_id, @categories.collect{|ctgr| [ctgr.name, ctgr.id]},
      {include_blank: t(".none")}, {class: "form-control"} %>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :name, t(".category_name") %>
    <div class="controls">
      <%= f.text_field :name, class: "form-control", id: "name",
        placeholder: t(".category_name") %>
    </div>
  </div>
  <br>
  <div class="form-actions add-category">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <%= link_to t(".cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/categories/edit.html.erb
<% provide :title, t(".new_category") %>
<% provide :button_text, t(".edit_category") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1><%= t ".edit_category" %></h1>
    <%= render "form" %>
  </div>
</div>

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/categories/index.html.erb
<% provide :title, t(".all_categories") %>
<% provide :title, t(".all_categories") %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1><%= t ".all_categories" %></h1>
    <%= link_to t(".new_category"), new_shop_owner_category_path,
      class: "btn btn-info" %>
    <hr>
    <div>
      <%= form_tag shop_owner_categories_path, method: :get do %>
        <%= select_tag :shop_id, options_for_select(current_user
          .shops.map{|f| [f.name, f.id]}), include_blank: t(".choice_a_shop"),
          onchange: "this.form.submit()" %> 
      <% end %>
    </div>
    <br>
    <div class="table-responsive">
      <table class="table table-vcenter table-striped">
        <tr class="display-categories">
          <th class="index text-center"><%= t".id" %></th>
          <th class="text-center"><%= t ".name" %></th>
          <th class="text-center"><%= t ".parent_id" %></th>
          <th class="text-center"><%= t ".owner " %></th>
          <th class="text-center"><%= t ".action" %></th>
        </tr>
        <% if @categories %>
          <% @categories.each do |category| %>
            <tr class="display-categories">
              <td class="index text-center"><%= category.id %></td>
              <td class="text-center"><%= category.name %></td>
              <td class="text-center">
                <% if category.parent_id.blank? %>
                  <%= t ".root" %>
                <% else %>
                  <%= category.parent_id %>
                <% end %>
              </td>
              <td>
                <% if category.shop_id.blank? %>
                  <%= t ".admin" %>
                <% else %>
                  <%= category.shop.name %>
                <% end %>
              </td>
              <td class="text-center">
                <% if can? :manage, category %>
                  <%= link_to edit_shop_owner_category_path(category),
                    class: "btn btn-default" do %>
                    <i class="fa fa-pencil-square-o"><%= t ".edit" %></i>
                  <% end %>
                  <%= link_to shop_owner_category_path(category), method: :delete,
                    data: {confirm: t("sure")}, class: "btn btn-default" do %>
                    <i class="fa fa-trash"><%= t ".delete" %></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="text-center">
      <%= will_paginate %>
    </div>
  </div>
</div>

Downloads/demo-fcafe-demo-v2/app/views/shop_owner/categories/new.html.erb
<% provide :title, t(".new_category") %>
<% provide :button_text, t(".new_category") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1><%= t ".new_category" %></h1>
    <%= render "form" %>
  </div>
</div>